server:
  port: 18084


spring:
  application:
    name: dubbo-spring-consumer

dubbo:
  spring:
    provider:
      version: 1.0.0
  registry:
    address: zookeeper://112.124.52.75:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  metadata-report:
    timeout: 30000
  config-center:
    timeout: 30000