server:
  port: 8001
spring:
  application:
    name: hailtaxi-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    #Consul配置
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        #注册到Consul中的服务名字
        service-name: ${spring.application.name}
        #注册的服务的实例 Id，最好不要重复，这里参考官网建议的方式 带随机数
        #instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.i nstance_id:${random.value}}}
        # 自定义实例id为:应用名:ip:port
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        prefer-ip-address: true
        # 开启服务注册
        register: true
        # 开启服务发现
        enabled: true
        #2 分钟之后健康检查未通过取消注册
        health-check-critical-timeout: 2m
        #consul 健康检查的轮询周期
        health-check-interval: 10s
    gateway:
      enabled: true
      routes:
        - id: hailtaxi-driver
          uri: lb://hailtaxi-driver
          predicates:
            - Path=/driver/**
            - Cookie=logo,itheima
            - Header=X-Request-Id,itheima
            - My=Auth,xxx
          filters:
            - AddRequestHeader=X-Request-Foo,Bar
            - My=token,hahaha
        - id: hailtaxi-order
          uri: lb://hailtaxi-order
          predicates:
            - Path=/order/**

management:
  endpoint:
    health:
      show-details: always
