spring:
  redis:
    host: 192.168.88.128
    port: 9010
    jedis:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    database: 0
