server:
  port: 18081

spring:
  application:
    name: dubbo-springboot-demo-provider

dubbo:
  scan:
    base-packages: com.yida
  protocol:
    name: dubbo  # Dubbo 通讯协议
    port: -1  # Dubbo服务提供的端口， 配置为-1，代表为随机端口 默认20880
  registry:
    address: zookeeper://112.124.52.75:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  metadata-report:
    timeout: 30000
  config-center:
    timeout: 30000
  spring:
    provider:
      version: 1.0.0
